apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-musthave-ns-xyz
  namespace: openshift-acm-policies
  annotations:
    policy.open-cluster-management.io/standards: Demo
    policy.open-cluster-management.io/categories: Demo
    policy.open-cluster-management.io/controls: Demo
spec:
  remediationAction: enforce
  disabled: false
  
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-namespace
        spec:
          remediationAction: enforce
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: "xyz"
